[package]
name = "dummy-rust"
version = "0.1.0"
authors = ["andrei-marinica <andrei.marinica@elrond.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
elrond-wasm = { path = "../elrond-wasm" }